name: GitHub CI

on:

  pull_request:

  push:

  schedule:
    - cron: 0 0 * * 0

jobs:

  build-test:

    strategy:
      matrix:
        dir:
          - 6
          - 7
          - 8
          - 9

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: docker system prune --all --force --volumes
      - name: Happy Eyeballs
        run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

      - name: Build Image
        working-directory: ${{ matrix.dir }}
        run: docker build -t gcc:${{ matrix.dir }} .

      - name: Run Tests
        run: |
          git clone --depth 1 https://github.com/docker-library/official-images.git ~/oi
          ~/oi/test/run.sh gcc:${{ matrix.dir }}

      - name: '"docker images"'
        run: docker images
